apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    cluster: edge-cluster
spec:
  selector:
    app: redis
    cluster: edge-cluster
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    cluster: edge-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      cluster: edge-cluster
  template:
    metadata:
      labels:
        app: redis
        cluster: edge-cluster
    spec:
      nodeSelector:
        allocating: car-service
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    cluster: cloud-cluster
spec:
  selector:
    app: redis
    cluster: cloud-cluster
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    cluster: cloud-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      cluster: cloud-cluster
  template:
    metadata:
      labels:
        app: redis
        cluster: cloud-cluster
    spec:
      nodeSelector:
        allocating: car-service
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379

