apiVersion: v1
kind: Service
metadata:
  name: gateway-service-lucas
  labels:
    user: lucas
spec:
  selector:
    app: gateway-service-lucas
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-lucas
  labels:
    user: lucas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-lucas
  template:
    metadata:
      labels:
        app: gateway-service-lucas
    spec:
      nodeSelector:
        user-allocating: lucas
      containers:
        - name: gateway-service-lucas
          image: jvcameros/trackerped:latest
          ports:
            - containerPort: 8000
          env:
            - name: USER_NAME
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-joe
  labels:
    user: joe
spec:
  selector:
    app: gateway-service-joe
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30085

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-joe
  labels:
    user: joe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-joe
  template:
    metadata:
      labels:
        app: gateway-service-joe
    spec:
      nodeSelector:
        user-allocating: joe
      containers:
        - name: gateway-service-lucas
          image: jvcameros/trackerped:latest
          ports:
            - containerPort: 8000
          env:
            - name: USER_NAME
              value: "8"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-car11
  labels:
    user: car11
spec:
  selector:
    app: gateway-service-car11
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-car11
  labels:
    user: car11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-car11
  template:
    metadata:
      labels:
        app: gateway-service-car11
    spec:
      nodeSelector:
        user-allocating: car11
      containers:
        - name: gateway-service-car11
          image: jvcameros/trackercar:latest
          ports:
            - containerPort: 8000
          env:
            - name: USER_NAME
              value: "car11"

